version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: bookingruk_mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app_network

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    environment:
      NODE_ENV: ${NODE_ENV}
      FRONTEND_URL: ${FRONTEND_URL}
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 3306
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
    ports:
      - "3001:3001"
    volumes:
      - ./back:/app
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        NUXT_PUBLIC_AUTH_URL: ${FRONTEND_URL}
        NUXT_PUBLIC_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        NUXT_GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    container_name: bookingruk_frontend
    environment:
      NITRO_HOST: 0.0.0.0
      NITRO_PORT: 3000
      NUXT_PUBLIC_AUTH_URL: ${FRONTEND_URL}
      NUXT_PUBLIC_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      NUXT_GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      NUXT_PUBLIC_API_BASE_URL: ${NUXT_PUBLIC_API_BASE_URL}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: bookingruk_nginx
    restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bookingruk_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - app_network

  # certbot:
  #   image: certbot/certbot
  #   container_name: bookingruk_certbot
  #   volumes:
  #     - ./certbot/www:/var/www/certbot
  #     - ./certbot/conf:/etc/letsencrypt
  #   entrypoint: sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot --email kittipon.nw@gmail.com --agree-tos --no-eff-email -d bookingmeetingroom.th.app.ruk-com.cloud"

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
